name: check-changelog-update
on:
  pull_request:

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
      backend-docker-image-tag: ${{ (github.base_ref == 'main' || github.base_ref == 'staging') && (github.base_ref == 'staging' && github.base_ref || 'latest') || 'dev' }}
  check-changelog-update:
    uses: ./.github/workflows/has-file-changed.yml
    with:
      filePath: CHANGELOG.md
