name: check-changelog-update
on:
  pull_request:

jobs:
  check-changelog-update:
    runs-on: ubuntu-latest
    steps:
      - name: View context attributes
        uses: actions/github-script@v6
        with:
          script: console.log(context)

      - run: npm install semver
      - uses: actions/github-script@v6
        name: Log diff result
        with:
          script: |
            const diff_url = context.payload.pull_request.diff_url
            const diff = await github.request(diff_url)
            console.log(diff)

            var parse = require('parse-diff');
            var files = parse(diff);
            console.log(JSON.stringify(files, null, 2))
