name: interface-with-docker
on:
  # Allow this workflow to be triggered via a button
  workflow_dispatch:

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'

  interface-with-docker:
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.15.0-chrome96-ff94
    services:
      db:
        image: mysql
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: rootPassword
    steps:
      - uses: actions/checkout@v2
      - name: install Docker client
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update
          apt-get -y install --no-install-recommends docker.io
      # - name: run service container
      #   run: docker run --rm --detach --network ${{ job.container.network }} --name db mysql
      - name: show running containers
        run: docker ps
      - name: show logs
        run: docker logs ${{ job.services.db.id }}
      - name: inspect service container
        run: docker inspect ${{ job.services.db.id }}
      - name: run inside service container
        run: docker exec ${{ job.services.db.id }} echo "Hello world"
      - name: stop apache2 container
        if: always()
        run: docker stop mysql
